### ISSUE TITLE
Rotate Downloads

### ISSUE THREAD

**Issue by DarrenRainey** [steamcache/monolithic#14]
### Describe the issue you are having
Can you add an option to replace old data when the drive reaches a certain capacity e.g if the drive is nearly full start deleting/replacing the oldest files.

### How are you running the container(s)?
```
HOST_IP=`hostname -I | cut -d' ' -f1`
docker run --restart unless-stopped --name steamcache-dns --detach -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=$HOST_IP steamcache/steamcache-dns:latest
docker run --restart unless-stopped --name sniproxy --detach -p 443:443 steamcache/sniproxy:latest
echo Please configure your dhcp server to serve dns as $HOST_IP

```

### DNS Configuration
```
Google DNS
```
### Output of container(s)
```
<!-- Paste any output from the containers here - This will help us identify any issues faster -->
```

**Comment by VibroAxe** [comment]
@DarrenRainey this is already present, if you set the cache size parameters correct for your drive monolithic will automatically rotate out the oldest files when it hits that capacity

https://github.com/steamcache/monolithic#tweaking-cache-sizes
