### ISSUE TITLE
sniproxy is downloading new copies

### ISSUE THREAD

**Issue by nem1611** [steamcache/monolithic#19]
### Describe the issue you are having

Hello, I am having an issue when I am running the sniproxy with this current configuration that appears to be downloading new copies of game updates some place instead of in the lancache repo....not sure if this is an previous issue or not

### How are you running the container(s)?
```
sudo docker run --restart unless-stopped --name steamcache-dns --detach -p 172.16.10.235:53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=172.16.10.235 steamcache/steamcache-dns:latest
sudo docker run --restart unless-stopped --name lancache --detach -v /mnt/lancache/data:/data/cache -v /mnt/lancache/logs:/data/logs -p 172.16.10.235:80:80  steamcache/monolithic:latest
sudo docker run --restart unless-stopped --name sniproxy --detach -p 172.16.10.235:443:443 steamcache/sniproxy:latest
```

**Comment by VibroAxe** [comment]
Hi there

Sniproxy is not a caching engine, it merely allows us to run http caching on mixed content domains

If you are on Comcast it appears the are some domains which need black holing?

**Comment by nem1611** [comment]
right sniproxy is not...but for example when I am downloading a steam game/update...it appears in docker stats that sniproxy will have high utilization while the lancache docker is completely idle and no new entries are created in the access.log

once the update is completed, ill remove it and start the download again as a test and sniproxy is again at high utilization with the lancache docker idle and no new entries...

yes I am on comcast, not sure how to do the black holing...im going to research that I suppose while clearing out my cache and re-installing

**Comment by VibroAxe** [comment]
Check out https://github.com/steamcache/steamcache-dns/issues/48 this should point you in the right direction
