### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nyemenzo** [steamcache/monolithic#20]
Can we use this to cache other streaming website like youtube or social media like facebook?

**Comment by GotenXiao** [comment]
Unfortunately not. Both YouTube and Facebook are HTTPS-only sites, we can't cache their content. Also, Facebook, being a very dynamic website, is a particularly poor candidate for caching - the content varies heavily by user and page load, whereas the content that is mostly passed through the caches from a content distribution network is specifically generic (i.e. consistent between multiple users).

Even if they were to use unencrypted HTTP, many of the streaming sites use protocols such as [HLS](https://en.wikipedia.org/wiki/HTTP_Live_Streaming) and [DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP), which reduce the effectiveness of a cache - clients may receive a differing quality level output, and the cache would likely only see small fragments of the total content stream.
