### ISSUE TITLE
Run 2nd cache for WSUS

### ISSUE THREAD

**Issue by BurningTheSky** [steamcache/monolithic#27]
### Describe the issue you are having
I would like to run a 2nd cache just for WSUS updates so that I can have them stored on slower storage with a shorter retention period but I am not sure of the correct context for the commands, do I just run a 2nd container with default settings and control access to it via the DNS?

### How are you running the container(s)?
docker run --restart unless-stopped --name lancache --detach -v /cache/data:/data/cache -v /cache/logs:/data/logs -p 192.168.0.81:80:80 -p 192.168.0.82:80:80 -p 192.168.0.83:80:80 -p 192.168.0.84:80:80 -e CACHE_MEM_SIZE=4000m -e CACHE_DISK_SIZE=1000g  steamcache/monolithic:latest
docker run --restart unless-stopped --name wsuscache --detach -v /wsus/data:/data/cache -v /wsus/logs:/data/logs -p 192.168.0.85:80:80 -e CACHE_MEM_SIZE=4000m -e CACHE_DISK_SIZE=500g -e CACHE_MAX_AGE 183d steamcache/monolithic:latest

### DNS Configuration
docker run --restart unless-stopped --name steamcache-dns --detach -p 192.168.0.80:53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP="192.168.0.81 192.168.0.82 192.168.0.83 192.168.0.84" -e WSUSCACHE_IP="192.168.0.85" -e UPSTREAM_DNS=1.1.1.1 steamcache/steamcache-dns:latest
docker run --restart unless-stopped --name sniproxy --detach -p 443:443 steamcache/sniproxy:latest

### Output of container(s)
$ docker run --restart unless-stopped --name wsuscache --detach -v /wsus/data:/data/cache -v /wsus/logs:/data/logs -p 192.168.0.85:80:80 -e CACHE_MEM_SIZE=4000m -e CACHE_DISK_SIZE=500g -e CACHE_MAX_AGE 183d steamcache/monolithic:latest
Unable to find image '183d:latest' locally
docker: Error response from daemon: pull access denied for 183d, repository does not exist or may require 'docker login'.
See 'docker run --help'

**Comment by VibroAxe** [comment]
Yeah, just starting a second container should be fine.

You've missed an equals in your 2nd docker run, try the following

`docker run --restart unless-stopped --name wsuscache --detach -v /wsus/data:/data/cache -v /wsus/logs:/data/logs -p 192.168.0.85:80:80 -e CACHE_MEM_SIZE=4000m -e CACHE_DISK_SIZE=500g -e CACHE_MAX_AGE=183d steamcache/monolithic:latest`
