### ISSUE TITLE
R+ games caching

### ISSUE THREAD

**Issue by jesgeerts** [steamcache/monolithic#29]
Is there a possibility to cache rockstar games? Like when you got a RockstarGames key that you're able to cache that game too instead by using steam etc?

**Comment by VibroAxe** [comment]
Hi @jesgeerts

Monolithic should already be caching r* unless they have changed domains recently.

https://github.com/uklans/cache-domains/blob/master/rockstar.txt

Are you telling us this this no longer works?

J

**Comment by jesgeerts** [comment]
@VibroAxe No, I'm not telling that isn't working but it was just a general question.
