### ISSUE TITLE
Update handling

### ISSUE THREAD

**Issue by ztrouy** [steamcache/monolithic#34]
I feel weird asking this in the format of an issue, but that is what the README informed me to do if I did not find the information I was looking for in the FAQ. Additionally I was unable to find this information online via search or in previous “issues”.

My question is quite simple hopefully! If a game was already cached on the server, and then an update for the game was released before one of the computers started downloading the cached version, would the entire game need to be re-downloaded? Or would it download the cached version from the cache, then download the update from the CDN and cache the update? Or something else entirely?

Thank you for your time, and if this question has already been answered before, I apologize deeply.

**Comment by VibroAxe** [comment]
(And never a problem to ask in the issues. Always happy to help)
