### ISSUE TITLE
Seemingly slow download speeds during cache warmup... thoughts? 

### ISSUE THREAD

**Issue by msmollin** [steamcache/monolithic#6]
### Describe the issue you are having
Was testing this out for an upcoming LAN party I help run tech support on, and everything is working pretty well, but I noticed on my router that I was only average 115 Mbit/s vs normally getting 200 mbps (my max bandwidth) when downloading from Steam. Obviously this could just be a fluke or some issue somewhere on the internet, but I wanted to know if there's anything simple I can do from my server to potentially troubleshoot it? My first thought was to load steamcmd just to make sure there wasn't anything weird going on on my network (really shouldn't be as router, server, and gaming pc are all on the same switch)

### How are you running the container(s)?
```
docker run \
  --restart unless-stopped \
  --name cache-steam \
  -v /data/cache:/data/cache \
  -v /data/logs:/data/logs \
  -e CACHE_MEM_SIZE=8000m \
  -e CACHE_DISK_SIZE=1500g \
  -p 80:80 \
  steamcache/monolithic:latest
```

### DNS Configuration
```
  docker run --restart unless-stopped --name steamcache-dns -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=192.168.100.223 steamcache/steamcache-dns:latest
```

**Comment by VibroAxe** [comment]
Hey.

Thanks for raising this. We've seen it a few times with generic as well, it looks to be an oddity with single client connections to steam (possibly some new rate limiting on their end based on a header we aren't proxying or something)

Leave it with us we'll keep digging.

If you see it happen on a service which isn't steam, I'd be very interested to know

**Comment by VibroAxe** [comment]
@msmollin We're trying to track this down, do you have a test setup you would be able to try the following image with: `steamcache/generic:proxy_read_timeout` we've had some rumours of a nginx config change making some improvements but by my reckoning they shouldn't do so would be good to get your feedback (Unfortunately there isn't a mono variant of this so you'll temporarily need a separate instance of generic for the steam in addition to your existing mono)

**Comment by VibroAxe** [comment]
Hey @msmollin 
So we've made a lot of progress on this in the last few days. We would appreciate any help you can give in testing the solution. Please head over to [steamcache/steamcache-dns#69](https://github.com/steamcache/steamcache-dns/pull/69) and follow the instructions there.

Thanks

**Comment by msmollin** [comment]
Hey @VibroAxe thats fantastic!! Sorry for not responding sooner! I'm traveling for the next 3 weeks, then moving the following week, so unfortunately life is gonna prevent me from testing anything seriously for a month. However, once that all calms down, I will totally give that a whirl.

**Comment by VibroAxe** [comment]
@msmollin not a problem, enjoy your holidays, with a bit of luck those changes will be live by then, if so I'll reference on here and point you at an updated readme

**Comment by VibroAxe** [comment]
Hey @msmollin 

https://github.com/steamcache/steamcache-dns/pull/69 is now merged and closed and should solve this problem. Please check the "Tuning your cache" section of the readme
